### ISSUE TITLE
convert failed:  'NoneType' object has no attribute 'file_name'

### ISSUE THREAD

**Issue by hellocatfood** [takecx/obj2schematic#6]
I'm trying to convert the attached file to a .schematic file but I'm getting an error and no ouput.

[3dmodel.zip](https://github.com/takecx/obj2schematic/files/6300048/3dmodel.zip)

Here's the command that I use:

`python3.9 Obj2SchemticConverter.py untitled.obj --output_dir output/ --h_max 50 --w_max 50`

And the error output

```
checking arguments...
start converting...
convert failed:  'NoneType' object has no attribute 'file_name'
Traceback (most recent call last):
  File "/home/hellocatfood/Desktop/Artechlaw/Software/obj2schematic/Obj2SchemticConverter.py", line 240, in <module>
	converter = Obj2SchematicConverter(
  File "/home/hellocatfood/Desktop/Artechlaw/Software/obj2schematic/Obj2SchemticConverter.py", line 38, in init
	self.df = self._create_obj_df(obj_path)
  File "/home/hellocatfood/Desktop/Artechlaw/Software/obj2schematic/Obj2SchemticConverter.py", line 46, in _create_obj_df
	vertices = self._analyze_mtl(obj_path, scene)
  File "/home/hellocatfood/Desktop/Artechlaw/Software/obj2schematic/Obj2SchemticConverter.py", line 59, in _analyze_mtl
	img_name = material.texture.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
```

**Comment by hellocatfood** [comment]
aha! I discovered that this occurs because the model does not have an image texture.

Are image textures required on all models or could there be a way to convert a model without it needing an image texture?

**Comment by takecx** [comment]
Hi! @hellocatfood 

Currently, support two `.obj` formats.
- [1. geometric vertices with (x, y, z, r, g, b)](https://github.com/takecx/obj2schematic#1-geometric-vertices-with-x-y-z-r-g-b)
- [2. .obj with .mtl](https://github.com/takecx/obj2schematic#2-obj-with-mtl)

> Are image textures required on all models or could there be a way to convert a model without it needing an image texture?

If your `.obj` format is [1. geometric vertices with (x, y, z, r, g, b)](https://github.com/takecx/obj2schematic#1-geometric-vertices-with-x-y-z-r-g-b), you don't need texture image.
If your `.obj` format is [2. .obj with .mtl](https://github.com/takecx/obj2schematic#2-obj-with-mtl), you need texture. image.

> I'm trying to convert the attached file to a .schematic file but I'm getting an error and no ouput.

Your `.mtl` file does not have `map_Kd`.
If you add `map_Kd` to your `.mtl` file, you might be able to convert it.

I hope this helps.

**Comment by hellocatfood** [comment]
Thank you, this helps greatly!
